name: lastfm-profile

on:
  schedule:
    - cron: '2 0 * * *'
  workflow_dispatch:

jobs:
  profile_stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lastfm to markdown
        uses: melipass/lastfm-to-markdown@v1.0.5
